### ISSUE TITLE
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]

### ISSUE THREAD

**Issue by alexkuc** [domainmod/domainmod#99]
Context: when adding domains without any associated fees domanMOD is asking to add fees.

Error: when adding fee for the first time and the currency is *not* USD, `HTTP ERROR 500` is raised. The following is printed to the error log:
````
[11-Mar-2019 08:52:52 UTC] PHP Warning:  file_get_contents(https://free.currencyconverterapi.com/api/v5/convert?q=USD_EUR&amp;compact=y): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad request
 in .../vendor/chetcuti/gjclasses/src/GJClasses/Remote.php on line 27
[11-Mar-2019 08:52:52 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. in .../classes/DomainMOD/Conversion.php:120
Stack trace:
#0 .../classes/DomainMOD/Conversion.php(120): PDO->prepare('\n              ...')
#1 .../classes/DomainMOD/Conversion.php(73): DomainMOD\Conversion->updateConversionRate(false, '1', '106', '1')
#2 .../assets/add/registrar-fee.php(152): DomainMOD\Conversion->updateRates('EUR', '1')
#3 {main}
  thrown in .../classes/DomainMOD/Conversion.php on line 120
````
Ps. full path is obfuscated for security reasons

Workaround: when creating fees for the **first**, specify USD currency. After that, fee can be changed into any other currency without any issues.

**Comment by chetcuti** [comment]
The above error was related to Free Currency Converter API, which we've unfortunately had to remove from DomainMOD as a currency conversion option, as their free accounts now require API keys. I've gone through tough and cleaned up Conversion.php a bit to help reduce errors that may be encountered.

Thanks for the report!
